seed: 42
dry_run: false
validate_only: false

eos:
  type: "metamodel_adaptive_cse"
  calculate_durca: true
  ndat_metamodel: 100
  nmax_nsat: 25.0
  nb_CSE: 6
  ndat_CSE: 100
  cs2_high_threshold: 0.95
  cs2_low_threshold: 0.001
  crust_name: "DH"

tov:
  type: "gr"
  min_nsat_TOV: 0.75
  ndat_TOV: 100
  nb_masses: 100

prior:
  specification_file: "prior.prior"

likelihoods:
- type: constraints_eos
  enabled: true
- type: zero
  enabled: true
sampler:
  type: smc-rw
  n_particles: 10000
  n_mcmc_steps: 10
  target_ess: 0.9
  random_walk_sigma: 0.1
  n_eos_samples: 10000
  output_dir: ./outdir/

postprocessing:
  enabled: true
  make_cornerplot: false
  make_massradius: true
  make_pressuredensity: true